apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app
  labels:
    app: golang-app
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: golang-app
    spec:
      containers:
      - name: golang-app
        image: bachdangtuan/golang-giaiphuongtrinh:latest
        tty: true
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: "1Gi"
        ports:
        - containerPort: 7000
          name: "7000-port"