kind: Service
apiVersion: v1
metadata:
 namespace: app-tuan
 name: external-postgres
spec:
 ports:
 - port: 5432
   targetPort: 5432
---
kind: Endpoints
apiVersion: v1
metadata:
 namespace: app-tuan
 name: external-postgres
subsets:
 - addresses:
     - ip: 10.0.0.132
   ports:
     - port: 5432